### ISSUE TITLE
The need for zrep:sent property

### ISSUE THREAD

**Issue by ghost** [isaaceindhoven/zrep-expire#1]
Hello,

As far as I can interpret, the zrep:sent property queried from the script is not needed for normal operation. Is it OK to remove it from the script?

The reason I am asking is because the snapshots I am dealing with do not have that property set - I am doing reverse zrep, a.k.a. pull replication.

---
Regards,
Biser

**Comment by ghost** [comment]
Oh, this is documented in the README, my bad.

However, the question still remains -- how to use zrep-expire with zrep pull. At the moment I've removed the zrep:sent check and it works. Maybe use another zrep property to check for zrep ownership?

**Comment by tinuzz** [comment]
Hello Biser,

I have been working on a new version of this script, which I just pushed to the repository. It is a complete rewrite, using a different scheme for specifying retentions. In the new version, the check for the `zrep:sent` propery is gone. The new version just checks whether the snapshot name matches zrep's naming scheme, but that check can be disabled with a command line switch.

I must say though, that I don't quite understand the issue. I also use zrep in reverse mode, and all snapshots on the backup server have the `zrep:sent` propery set.

If you decide to move to the new version, please let me know what you think.

Best regards,
Martijn.
