### ISSUE TITLE
python3 compatibility

### ISSUE THREAD

**Issue by t-oster** [isaaceindhoven/zrep-expire#2]
Hi,

I am using your script on ArchLinux, however python2 will be abandoned january 2020. Would it be a big amount of work to port this script to python3?

**Comment by tinuzz** [comment]
Hi,

As a matter of fact, I already did the work a while ago, but I haven't pushed those changes to this repo. I just updated the script and the README file to reflect what I am currently running myself.

Besides the switch to Python3, there is another big (but backwards compatible) change. The script now has a '-t'option, that allows you to specify which _ZREPTAGs_ to act on. If you don't use ZREPTAG explicitly, the tag will be 'zrep', and that is the default.

See http://www.bolthole.com/solaris/zrep/zrep.documentation.html#multi for information on the use of ZREPTAG.

Best regards,
Martijn.

**Comment by t-oster** [comment]
Thanks for the quick answer. I will test tomorrow and create an AUR package. The t option comes handy for me since I use zfs-auto-snapshot on the main server and push the backups with zrep to the backup server, so zrep takes care of the 5 zrep snapshots and I use your script to exprie the zfs-auto-snapshot ones.
